version: "3.3"
services:
  reporting-service:    
    container_name: reporting-service
    build:      
      context: ..
      dockerfile: ./Assessment/Dockerfile
    depends_on: [ mssql ]        
    ports:
      - "8080:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Assessment123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "1433:1433" 
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672